# Generated by Django 3.2.7 on 2021-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('slug', models.SlugField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
